repos:
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort src/
        language: system
        pass_filenames: false
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py36-plus
        language: python
        types: [python]
        pass_filenames: true
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black src/
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: poetry run flake8 src/
        language: system
        pass_filenames: false